version: '3'
services:
  luigi:
    image: stockport/luigid
    volumes:
      - ./etc/luigi:/etc/luigi
      - ./var/luigi:/var/lib/luigi-server/
    ports:
      - '8082:8082'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  arnica:
    image: mlhamel/arnica
    ports:
      - "8000:8000"
    depends_on:
      - db
      - luigi
volumes:
  db-data:
