version: '3.3'
services:
  luigi:
    image: stockport/luigid
    ports:
      - '8082:8082'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  db-data: