# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=1000)),
                ('commercial_flow', models.CharField(max_length=1000)),
                ('travellers_flow', models.CharField(max_length=1000)),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
