# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borderwaittime', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tick',
            unique_together=set([('office', 'updated')]),
        ),
    ]
