# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao24', models.CharField(max_length=64)),
                ('callsign', models.CharField(max_length=64)),
                ('origin_country', models.CharField(max_length=64)),
                ('time_position', models.IntegerField()),
                ('time_velocity', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('on_ground', models.BooleanField()),
                ('velocity', models.FloatField()),
                ('heading', models.FloatField()),
                ('vertical_rate', models.FloatField()),
                ('sensors', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set([('icao24', 'time_position', 'time_velocity')]),
        ),
    ]
