# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='altitude',
            field=models.FloatField(help_text='in meters.', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='callsign',
            field=models.CharField(help_text='callsign of the vehicle. Can be None if no callsign has been received.', max_length=64),
        ),
        migrations.AlterField(
            model_name='state',
            name='heading',
            field=models.FloatField(help_text='# in decimal degrees (0 is north). Can be None if information not present.', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='icao24',
            field=models.CharField(help_text='ICAO24 address of the transmitter in hex string representation.', max_length=64),
        ),
        migrations.AlterField(
            model_name='state',
            name='latitude',
            field=models.FloatField(help_text='in ellipsoidal coordinates (WGS-84) and degrees.', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='longitude',
            field=models.FloatField(help_text='in ellipsoidal coordinates (WGS-84) and degrees.', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='on_ground',
            field=models.BooleanField(help_text='true if aircraft is on ground (sends ADS-B surface position reports).'),
        ),
        migrations.AlterField(
            model_name='state',
            name='origin_country',
            field=models.CharField(help_text='inferred through the ICAO24 address', max_length=64),
        ),
        migrations.AlterField(
            model_name='state',
            name='sensors',
            field=models.CharField(help_text='serial numbers of sensors which received messages from the vehicle within the validity periodof this state vector. Can be None if no filtering for sensor has been requested.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='time_position',
            field=models.IntegerField(help_text='seconds since epoch of last position report. Can be None if there was no position report received by OpenSky within 15s before.', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='time_velocity',
            field=models.IntegerField(help_text='seconds since epoch of last velocity report. Can be None if there was no velocity report received by OpenSky within 15s before.', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='velocity',
            field=models.FloatField(help_text='over ground in m/s. Can be None if information not present'),
        ),
        migrations.AlterField(
            model_name='state',
            name='vertical_rate',
            field=models.FloatField(help_text='# in m/s, incline is positive, decline negative. Can be None if information not present.', null=True),
        ),
    ]
